from scapy.all import *
import random
import time
import os

def generate_benign(count=100, out_file="benign.pcap"):
    print(f"Generating {out_file}...")
    packets = []
    base_time = time.time() - 3600 # 1 hour ago
    
    for i in range(count):
        src_ip = f"192.168.1.{random.randint(10, 50)}"
        dst_ip = f"10.0.0.{random.randint(10, 50)}"
        sport = random.randint(1024, 65535)
        dport = random.choice([80, 443, 53])
        
        # Simple TCP handshake
        pkt = Ether()/IP(src=src_ip, dst=dst_ip)/TCP(sport=sport, dport=dport, flags="S")
        pkt.time = base_time + (i * 0.1)
        packets.append(pkt)
        
    wrpcap(out_file, packets)

def generate_syn_flood(count=1000, target="10.0.0.1", out_file="attack_syn_flood.pcap"):
    print(f"Generating {out_file}...")
    packets = []
    base_time = time.time() - 3000
    
    for i in range(count):
        # Spoofed source IPs
        src_ip = f"{random.randint(1,254)}.{random.randint(1,254)}.{random.randint(1,254)}.{random.randint(1,254)}"
        sport = random.randint(1024, 65535)
        
        pkt = Ether()/IP(src=src_ip, dst=target)/TCP(sport=sport, dport=8080, flags="S")
        pkt.time = base_time + (i * 0.001) # fast rate
        packets.append(pkt)
        
    wrpcap(out_file, packets)

def generate_recon(target="10.0.0.1", src="192.168.1.100", out_file="attack_recon.pcap"):
    print(f"Generating {out_file}...")
    packets = []
    base_time = time.time() - 2500
    
    for port in range(1, 1001):
        pkt = Ether()/IP(src=src, dst=target)/TCP(sport=54321, dport=port, flags="S")
        pkt.time = base_time + (port * 0.01)
        packets.append(pkt)
        
    wrpcap(out_file, packets)

def generate_c2(src="192.168.1.200", dst="10.0.0.99", port=9999, out_file="attack_c2.pcap"):
    print(f"Generating {out_file}...")
    packets = []
    base_time = time.time() - 2000
    
    # 20 beacons, 30s interval, slight jitter
    for i in range(20):
        interval = 30 + random.uniform(-2, 2)
        base_time += interval
        sport = random.randint(1024, 65535)
        
        # simple SYN to simulate the connection
        pkt = Ether()/IP(src=src, dst=dst)/TCP(sport=sport, dport=port, flags="S")
        pkt.time = base_time
        packets.append(pkt)
        
    wrpcap(out_file, packets)

def generate_dns_tunnel(src="192.168.1.150", dst="8.8.8.8", out_file="attack_dns_tunnel.pcap"):
    print(f"Generating {out_file}...")
    packets = []
    base_time = time.time() - 1000
    
    for i in range(50):
        # random high entropy subdomain
        subdomain = "".join(random.choices("abcdefghijklmnopqrstuvwxyz0123456789", k=30))
        qname = f"{subdomain}.evil.com"
        
        pkt = Ether()/IP(src=src, dst=dst)/UDP(sport=random.randint(1024, 65535), dport=53)/DNS(rd=1, qd=DNSQR(qname=qname))
        pkt.time = base_time + (i * 0.5)
        packets.append(pkt)
        
    wrpcap(out_file, packets)

def main():
    generate_benign()
    generate_syn_flood()
    generate_recon()
    generate_c2()
    generate_dns_tunnel()
    print("Done generating PCAPs.")
    print("attack_tls_malware.pcap and attack_exfil.pcap are NOT generated by "
          "this script -- see the note below.")

# --- attack_tls_malware.pcap / attack_exfil.pcap -----------------------
# Unlike every pcap above (scapy-crafted packets with no real payload --
# fine for ddos/recon/c2/dga, whose detectors key off rate/fan-out/timing/
# query-name, never byte volume), the tls and exfil detectors gate on real
# byte counts (tls_malware.py rejects total_bytes < 100; exfil.py rejects
# orig_bytes < 1000) and classify on byte_ratio/bytes_per_sec computed
# from those counts. A scapy pcap with header-only packets would report
# 0 bytes and never reach either model, so these two pcaps are real
# captured traffic instead, generated once with:
#
#   openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem \
#       -days 2 -nodes -subj "/CN=localhost"
#   python3 upload_sink.py 8443 --tls cert.pem key.pem &   # TLS sink
#   python3 upload_sink.py 8090 &                          # plain HTTP sink
#   docker exec -d zeek_monitor zeek -C -i lo -f "tcp port <port>" \
#       -w /tmp/trace.pcap
#   curl -k --limit-rate 300000 -X POST --data-binary @bigfile.bin \
#       https://127.0.0.1:8443/upload   # (or http://127.0.0.1:8090/upload)
#
# `--limit-rate` throttles an ~800KB upload to ~2.5s: fast enough that the
# two temporary Zeek trace-writer processes sharing loopback with the
# live -i lo process don't drop packets (a 40s throttle was tried first
# and reliably corrupted the TLS handshake reassembly -- see ML_MODELS.md),
# but slow enough to clear both detectors' `duration < 0.1s` reject guard.
# This lands the resulting flow (orig_bytes ~800K, resp_bytes in the low
# hundreds, byte_ratio in the hundreds-to-thousands) inside the
# "bulk-upload" / "HIGH_UPLOAD" shape both models were trained to
# recognize -- verified directly against TLSMalwareDetector.process() and
# ExfilDetector.process() (HIGH confidence, both calibrated) before being
# committed as the replay pcap.
#
# `upload_sink.py` (a throwaway local HTTP/HTTPS server that reads and
# discards a POST body) is not checked into this repo -- it's a few lines
# of http.server.BaseHTTPRequestHandler, regenerate it if you need to
# rebuild these pcaps.

if __name__ == "__main__":
    main()
