"""
Download a bounded, real-malware-DGA domain sample from UMUDGA and cache it
offline. Run ONCE before retraining the DGA model -- never called at
runtime, same one-way-compliant pattern as download_ja3_blacklist.py.

Source: UMUDGA (University of Murcia Domain Generation Algorithm Dataset) --
Zago, Gil Pérez & Martínez Pérez, "UMUDGA: a dataset for profiling DGA-based
botnet," Computers & Security, 2020 (DOI 10.1016/j.cose.2020.101719).
Dataset DOI: 10.17632/y8ph45msv8.1 (Mendeley Data). MIT licensed.

Over 30M domains generated by *actually executing* 50 real malware DGA
families' own code in a controlled environment -- real malware output, not
a synthetic re-implementation of a published algorithm's shape (which is
what train_dga.py's other 9 generators are, since no DGArchive access
exists -- see ML_MODELS.md). This closes that gap for a bounded subset.

Two earlier candidate sources were tried and rejected, for the record:
Bambenek Consulting's feed (osint.bambenekconsulting.com) requires a
contacted, manually-issued license even for research/non-profit use -- not
a plug-and-fetch download despite being nominally "free" -- and Netlab 360's
feed (data.netlab.360.com) has an SSL certificate that expired in Dec 2023
and the host is currently unreachable from this environment. Both are
documented here rather than silently swapped, in case either becomes
usable again later.

UMUDGA's per-family folder IDs are opaque UUIDs -- the dataset's own public
file-listing API does not expose the malware family name per folder, and
the project's GitHub wiki only documents feature statistics, not a
folder->family key. Rather than guess (or silently claim a specific family
name is confirmed when it isn't), each row is tagged with its real source
folder ID and a purely descriptive shape_hint (inferred by eye from the
sample content -- e.g. "dict_concat_hyphenated" for Suppobox-style English-
word concatenation, "random_alnum_fixed_len" for fixed-length random
charset) -- never asserted as the authoritative family name. The dataset's
own DOI is the authoritative source for the official 50-family roster.

Output: training/dga_real_umudga.csv (domain, source_folder_id, shape_hint)
"""
import csv
import json
import urllib.request
from pathlib import Path

FILES_API = "https://data.mendeley.com/api/datasets/y8ph45msv8/files?version=1"
OUTPUT = Path(__file__).parent.parent / "training" / "dga_real_umudga.csv"

# Mendeley's edge (Cloudflare) returns 403 for urllib's default
# "Python-urllib/x.y" user-agent string -- a bot-filtering rule, not an
# auth requirement (the same endpoint works fine over curl with no
# credentials). A normal browser-style UA clears it.
_HEADERS = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) ODIN-dataset-fetch/1.0"}


def _get(url, timeout):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers=_HEADERS), timeout=timeout
    )

# Deterministic pick: 12 distinct folders (of 37 that carry a 100,000-domain
# sample file) spread evenly across the listing, not just the first N, so
# the sample isn't biased toward whatever order Mendeley happened to upload in.
N_FOLDERS = 12
DOMAINS_PER_FOLDER = 500
SAMPLE_FILE = "100000.txt"

# Filled in by eye after inspecting each folder's first ~10 real domains --
# see module docstring for why this is a hint, not a confirmed family name.
SHAPE_HINTS = {
    0: "random_alnum_fixed_len",       # e.g. usyeeusiuaaayscg.org
    1: "random_alnum_variable_len",    # e.g. kxmzcrg.top
    2: "random_alnum_variable_len",    # e.g. odtvfpacyic.info
    3: "dict_concat_hyphenated",       # e.g. wedding-muscle.com
    4: "hex_hash_style",               # e.g. c00043ea763912a7d39e0930ecd10c31e3.to
    5: "random_alnum_fixed_len",       # e.g. qkdchxxxzn.com
    6: "random_alnum_with_digits",     # e.g. 9g2rdi9uga.net, 5g1xxzjvohrb5.com
    7: "random_alnum_variable_len",    # e.g. rtigowejscvol.biz
    8: "random_alnum_mixed_tld",       # e.g. wmfgrwgumcelx.ru, pidfksipycmyg.com
    9: "random_alnum_mixed_tld",       # e.g. bachdcb.me, frxdfuklw.ru
    10: "dict_concat_nohyphen",        # e.g. migrationispeopleofof.biz
    11: "random_alnum_variable_len",   # e.g. sauyxsjmubqmdjtrdm.com
}


def _list_files():
    with _get(FILES_API, timeout=20) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _pick_folders(files):
    by_folder = {}
    for f in files:
        by_folder.setdefault(f["folder_id"], {})[f["filename"]] = f
    eligible = sorted(fid for fid, d in by_folder.items() if SAMPLE_FILE in d)
    if len(eligible) < N_FOLDERS:
        raise RuntimeError(
            f"UMUDGA file listing only has {len(eligible)} folders with "
            f"{SAMPLE_FILE}, need {N_FOLDERS} -- dataset structure may have "
            f"changed; update N_FOLDERS/SHAPE_HINTS by hand before re-running."
        )
    step = len(eligible) / N_FOLDERS
    picked = [eligible[int(i * step)] for i in range(N_FOLDERS)]
    return [(fid, by_folder[fid][SAMPLE_FILE]) for fid in picked]


def download():
    files = _list_files()
    picked = _pick_folders(files)

    rows = []
    for idx, (folder_id, meta) in enumerate(picked):
        url = meta["content_details"]["download_url"]
        with _get(url, timeout=30) as resp:
            lines = resp.read().decode("utf-8", errors="ignore").splitlines()
        if len(lines) < DOMAINS_PER_FOLDER:
            raise RuntimeError(
                f"Folder {folder_id} only had {len(lines)} domains, expected "
                f"~100,000 -- download may have been truncated or redirected "
                f"to an error page."
            )
        step = len(lines) / DOMAINS_PER_FOLDER
        sample = [lines[int(i * step)].strip() for i in range(DOMAINS_PER_FOLDER)]
        shape_hint = SHAPE_HINTS.get(idx, "unclassified")
        for domain in sample:
            if domain:
                rows.append((domain, folder_id, shape_hint))
        print(f"[umudga] folder {folder_id[:8]}... ({shape_hint}): "
              f"{len(sample)} domains sampled from {len(lines)}")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["domain", "source_folder_id", "shape_hint"])
        writer.writerows(rows)
    print(f"\nSaved {len(rows)} real malware-DGA domains "
          f"({len(picked)} folders x ~{DOMAINS_PER_FOLDER}) to {OUTPUT}")


if __name__ == "__main__":
    download()
